// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryWPF.Models;

public partial class Author
{
    [Key]
    public int AuthorID { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [NotMapped]
    public string FullName => $"{FirstName} {LastName}";

    public int? BirthYear { get; set; }

    [StringLength(50)]
    public string Country { get; set; }

    public string Biography { get; set; }

    [InverseProperty("Author")]
    public virtual ICollection<Book> Books { get; set; } = new List<Book>();

    [ForeignKey("AuthorID")]
    [InverseProperty("Authors")]
    public virtual ICollection<Book> BooksNavigation { get; set; } = new List<Book>();
}