// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryWPF.Models;

public partial class BookSeries
{
    [Key]
    public int SeriesID { get; set; }

    [Required]
    [StringLength(100)]
    public string SeriesName { get; set; }

    public string Description { get; set; }

    public int? TotalBooks { get; set; }

    [InverseProperty("Series")]
    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}