// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryWPF.Models;

[Index("GenreName", Name = "UQ__Genres__BBE1C3395C84E686", IsUnique = true)]
public partial class Genre
{
    [Key]
    public int GenreID { get; set; }

    [Required]
    [StringLength(50)]
    public string GenreName { get; set; }

    [ForeignKey("GenreID")]
    [InverseProperty("Genres")]
    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}