// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryWPF.Models;

[Table("ReadingHistory")]
[Index("BookID", Name = "IX_ReadingHistory_Book")]
[Index("UserID", Name = "IX_ReadingHistory_User")]
[Index("UserID", "BookID", Name = "UQ_UserBook", IsUnique = true)]
public partial class ReadingHistory
{
    [Key]
    public int RecordID { get; set; }

    public int UserID { get; set; }

    public int BookID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastReadDate { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? ProgressPercent { get; set; }

    public bool? IsFinished { get; set; }

    [ForeignKey("BookID")]
    [InverseProperty("ReadingHistories")]
    public virtual Book Book { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("ReadingHistories")]
    public virtual User User { get; set; }
}