// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryWPF.Models;

[Index("UserID", Name = "IX_UserFavorites_User")]
[Index("UserID", "BookID", Name = "UQ_UserFavorite", IsUnique = true)]
public partial class UserFavorite
{
    [Key]
    public int FavoriteID { get; set; }

    public int UserID { get; set; }

    public int BookID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AddedDate { get; set; }

    public int? SortOrder { get; set; }

    [ForeignKey("BookID")]
    [InverseProperty("UserFavorites")]
    public virtual Book Book { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("UserFavorites")]
    public virtual User User { get; set; }
}